# Generated by Django 6.0.6 on 2026-06-15 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('headless_mode', models.BooleanField(default=True, help_text='Centang untuk mode otomatis (tidak tampil), tidak centang untuk mode manual (browser muncul)', verbose_name='Mode Headless')),
                ('default_max_results', models.IntegerField(default=50, help_text='Jumlah default tempat yang diambil setiap scraping', verbose_name='Maksimal Hasil Default')),
                ('scroll_count', models.IntegerField(default=8, help_text='Berapa kali scroll untuk memuat lebih banyak hasil', verbose_name='Jumlah Scroll')),
                ('delay_between_scroll', models.FloatField(default=1.5, help_text='Jeda antar scroll untuk menghindari block', verbose_name='Delay Antar Scroll (detik)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
            ],
            options={
                'verbose_name': 'Konfigurasi Scraper',
                'verbose_name_plural': 'Konfigurasi Scraper',
            },
        ),
        migrations.CreateModel(
            name='ScrapingLog',
            fields=[
                ('keyword', models.CharField(max_length=200, verbose_name='Keyword')),
                ('total_found', models.IntegerField(default=0, verbose_name='Total Ditemukan')),
                ('total_saved', models.IntegerField(default=0, verbose_name='Total Tersimpan')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Pesan Error')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Selesai')),
            ],
            options={
                'verbose_name': 'Log Scraping',
                'verbose_name_plural': 'Log Scraping',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=500, verbose_name='Nama Tempat')),
                ('category', models.CharField(blank=True, choices=[('masjid', 'Masjid'), ('toko_sembako', 'Toko Sembako'), ('restaurant', 'Restoran'), ('cafe', 'Cafe'), ('hotel', 'Hotel'), ('lainnya', 'Lainnya')], max_length=50, null=True, verbose_name='Kategori')),
                ('keyword', models.CharField(blank=True, help_text='Keyword yang digunakan saat scraping', max_length=200, verbose_name='Keyword Pencarian')),
                ('address', models.TextField(blank=True, verbose_name='Alamat Lengkap')),
                ('province', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Provinsi')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Kota/Kabupaten')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Kecamatan')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kode Pos')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telepon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('reviews_count', models.IntegerField(default=0, verbose_name='Jumlah Review')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('scraped_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Scrape')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Terakhir Diupdate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Tempat',
                'verbose_name_plural': 'Tempat-tempat',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['province', 'city'], name='scraper_dat_provinc_b7cf62_idx'), models.Index(fields=['category', 'keyword'], name='scraper_dat_categor_6dfd3a_idx')],
            },
        ),
    ]
