# Generated by Django 4.2.30 on 2026-06-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique identifier from Google Places API', max_length=255, verbose_name='Google Place ID'),
        ),
        migrations.AlterField(
            model_name='scraperconfig',
            name='headless_mode',
            field=models.BooleanField(default=True, help_text='Jalankan browser tanpa GUI (latar belakang)', verbose_name='Headless Mode'),
        ),
    ]
