# Generated by Django 6.0.6 on 2026-06-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraperconfig',
            name='headless_mode',
        ),
    ]
